import { mkdirSync, writeFileSync } from "fs";
import { dirname, relative, resolve } from "path";
import type {
  ComponentResolveResult,
  ComponentsContext,
  GenerateDtsOptions,
} from "../types";
import { isExportComponent, slash } from "./utils";
import { listAllComponents } from "./manager";

function stringifyLocal(rootPath: string, c: ComponentsContext) {
  const rel = `./${relative(rootPath, c.path)}`;
  const key = isExportComponent(c) ? c.name : "default";
  return `typeof import('${slash(rel).replace(/\.[jt]sx$/, "")}')['${key}']`;
}

function stringifyResolved(r: ComponentResolveResult) {
  const key = (r.type ?? "Export") === "Export" ? r.name : "default";
  return `typeof import('${r.from}')['${key}']`;
}

/**
 * Emit `<rootPath>/<filename>.d.ts` that augments the global scope with one
 * `const X: typeof import(...)` per known component — both local AST-scanned
 * ones (when `local` is on) and everything every resolver enumerates via `list()`.
 */
export function generateDts(options: GenerateDtsOptions) {
  const {
    components,
    rootPath = process.cwd(),
    filename = "components",
    resolvers,
    local,
  } = options;

  const lines: string[] = [];
  lines.push("/* generated by unplugin-react-components */");
  lines.push("/* eslint-disable */");
  lines.push("// @ts-nocheck");
  lines.push("export {}");
  lines.push("declare global {");

  if (local) {
    components.forEach((c) => {
      lines.push(`  const ${c.name}: ${stringifyLocal(rootPath, c)}`);
    });
  }

  for (const item of listAllComponents(resolvers))
    lines.push(`  const ${item.jsxName}: ${stringifyResolved(item)}`);

  lines.push("}");
  lines.push("");

  const dts = lines.join("\n");
  const outPath = resolve(rootPath, `${filename}.d.ts`);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, dts, "utf-8");

  return dts;
}
