import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, relative, resolve } from "path";
import type {
  ComponentResolveResult,
  ComponentsContext,
  GenerateDtsOptions,
} from "../types";
import { isExportComponent, slash } from "./utils";
import { listAllComponents } from "./manager";
import { createDebug } from "./debug";

const dbg = createDebug("dts");

function stringifyLocal(rootPath: string, c: ComponentsContext) {
  // `relative` produces e.g. `src/Hello.tsx` when the dts sits above the
  // component, or `../components/Hello.tsx` when it sits in a sibling dir
  // (`src/types/`). Only the first case needs a `./` prefix; the second
  // form is already valid TS path syntax.
  let rel = relative(rootPath, c.path);
  if (!rel.startsWith(".")) rel = `./${rel}`;
  const key = isExportComponent(c) ? c.name : "default";
  return `typeof import('${slash(rel).replace(/\.[jt]sx$/, "")}')['${key}']`;
}

function stringifyResolved(r: ComponentResolveResult) {
  const key = (r.type ?? "Export") === "Export" ? r.name : "default";
  return `typeof import('${r.from}')['${key}']`;
}

interface Entry {
  /** The declaration body — `typeof import('...')['...']`. */
  body: string;
  /** Where this declaration came from, for the conflict warning. */
  source: string;
  /** Local components win over resolver components on a name collision. */
  isLocal: boolean;
}

/**
 * Emit `<rootPath>/<filename>.d.ts` that augments the global scope with one
 * `const X: typeof import(...)` per known component — both local AST-scanned
 * ones (when `local` is on) and everything every resolver enumerates via `list()`.
 *
 * Dedupe rule: when the same identifier comes from both a local file and a
 * resolver (e.g. user's `App.tsx` vs antd v5's `App` component), the **local**
 * wins. A warning is logged so the user knows why their import path went one
 * way. Without this dedupe, the generated file had two `const App: ...` lines
 * — only saved by the `// @ts-nocheck` pragma at the top.
 */
export function generateDts(options: GenerateDtsOptions) {
  const {
    components,
    rootPath = process.cwd(),
    filename = "components",
    resolvers,
    local,
  } = options;

  // Map<identifier, Entry>. Insertion order is what we emit, but local entries
  // are written *before* resolver entries so the iteration order is stable.
  const entries = new Map<string, Entry>();

  if (local) {
    components.forEach((c) => {
      entries.set(c.name, {
        body: stringifyLocal(rootPath, c),
        source: c.path,
        isLocal: true,
      });
    });
  }

  for (const item of listAllComponents(resolvers)) {
    const existing = entries.get(item.jsxName);
    if (existing) {
      if (existing.isLocal) {
        // eslint-disable-next-line no-console
        console.warn(
          `[unplugin-react-components] dts: "${item.jsxName}" is both a local component ` +
            `(${existing.source}) and a resolver export (${item.from}). The local file wins; ` +
            `rename one to silence this warning.`,
        );
        continue;
      }
      // resolver vs resolver: keep first; second is a redundant duplicate.
      continue;
    }
    entries.set(item.jsxName, {
      body: stringifyResolved(item),
      source: item.from,
      isLocal: false,
    });
  }

  const lines: string[] = [];
  lines.push("/* generated by unplugin-react-components */");
  lines.push("/* eslint-disable */");
  lines.push("// @ts-nocheck");
  lines.push("export {}");
  lines.push("declare global {");
  // Emit names in a stable, deterministic order instead of `entries`'
  // insertion order. The watcher applies a component edit as delete-then-add,
  // which re-appends the changed component at the *end* of the `components`
  // Set — so insertion order would make its `const X: ...` line jump to the
  // bottom of the block on every edit, producing noisy git diffs. Sorting by
  // name keeps each declaration in a fixed spot: editing or adding one
  // component now touches only its own line. Code-unit comparison (not
  // `localeCompare`) so the output is identical across machines/locales.
  const sorted = [...entries.entries()].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  );
  for (const [name, entry] of sorted) {
    lines.push(`  const ${name}: ${entry.body}`);
  }
  lines.push("}");
  lines.push("");

  const dts = lines.join("\n");
  const outPath = resolve(rootPath, `${filename}.d.ts`);

  // Skip the write when the file content is already identical. The big win is
  // that the editor's TS server won't see a no-op file change → no needless
  // type-check pass. This matters because every chokidar `change` event on a
  // component file currently triggers `emitDts`, even when the file's *exports*
  // didn't change (the user just edited the JSX body).
  if (existsSync(outPath)) {
    try {
      if (readFileSync(outPath, "utf-8") === dts) {
        dbg(`skip write (identical) ${outPath}`);
        return dts;
      }
    } catch {
      // fall through to write
    }
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, dts, "utf-8");
  dbg(`wrote ${entries.size} component(s) → ${outPath}`);

  return dts;
}
